# Generated by Django 4.2.25 on 2025-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
