# Generated by Django 4.2.25 on 2025-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
